// Textos de la landing en español e inglés. La llave de idioma ("cucoarts-lang") es la misma que usa /rob.
export type Lang = 'es' | 'en';

const es = {
  htmlTitle: 'CUCO ARTS · Arte y cultura de Monterrey',
  nav: { store: 'Tienda', quote: 'Cotizador', murals: 'Murales', art: 'Arte por encargo', fresh: 'Nuevo', sell: 'Vende tu obra', expo: 'Expo en Santiago', live: 'Activa', events: 'Eventos', label: 'Secciones' },
  theme: { toDark: 'Modo noche', toLight: 'Modo día' },
  langBtn: { label: 'Switch to English', short: 'EN' },
  hero: {
    cornerL: 'CUCOARTS',
    cornerR: 'ARTE LOCAL',
    title: 'Descubre el Monterrey que existe más allá de los mapas.',
    lede: 'Compra obra original de artistas locales, encarga una pieza a tu medida o vende tu obra con nosotros.',
    cta: 'Visitar la tienda',
    cta2: 'Qué puedes hacer aquí',
    expo: 'Expo activa en Santiago',
    stamp: ['DEL NORTE', 'CON AMOR'],
    galleryLabel: 'Obra y fotografía de Monterrey',
  },
  credit: { art: 'Obra de', photo: 'Foto', zone: 'Zona cultural' },
  actionsTitle: '¿Qué quieres hacer hoy?',
  murals: {
    label: 'Murales · Nuevo',
    title: 'Tu muro, pintado por artistas de Monterrey',
    text: 'Desde 2019 producimos y gestionamos murales con pintores locales: conectamos tu idea con el artista indicado y llevamos el proyecto de principio a fin.',
    cta: 'Ver murales y proyectos',
    cta2: 'Cotizar un mural',
    stamp: ['MURALES', 'MTY'],
    alt: 'Mural pintado por artistas locales en Monterrey',
  },
  art: {
    label: 'Arte por encargo · Nuevo',
    title: 'Tu obra, a tu manera',
    text: 'Pintura, dibujo e ilustración hechos por artistas de Monterrey: cuéntanos tu idea y te conectamos con el artista ideal.',
    cta: 'Encargar mi obra',
    cta2: 'Ver cómo funciona',
    stamp: ['A TU', 'MEDIDA'],
    alt: 'Obra original de un artista local de Monterrey',
  },
  about: {
    label: 'Sobre CUCO ARTS',
    title: 'Descubre Monterrey a través de su arte y su cultura',
    text: [
      'CUCO ARTS es una plataforma para descubrir el arte, los artistas y los espacios creativos de Monterrey. En nuestra tienda en línea encontrarás obra original de artistas locales —pintura, grabado, ilustración y escultura— con envíos internacionales. También impulsamos exposiciones y colaboraciones culturales, y conectamos ideas con artistas para crear murales y obras a medida.',
      'A través de nuestro proyecto de zonas culturales, buscamos acercarte a quienes crean en la ciudad y explorar cómo el arte se vive en sus distintos territorios: Norte, Sur, Oriente, Centro y Poniente.',
    ],
    zonesTitle: 'Zonas culturales de Monterrey',
    zonesText: 'Explora la ciudad a través de sus artistas, sus espacios creativos y las historias que hacen única a cada zona.',
    zonesLabel: 'Zonas culturales',
    zones: ['Norte', 'Sur', 'Oriente', 'Centro', 'Poniente'],
    soon: 'Mapa cultural próximamente',
  },
  cards: {
    store: { h: 'Explora la tienda', p: 'Obra original de artistas locales de Monterrey.', cta: 'Ir a store.cucoarts.com' },
    quote: { h: 'Cotizador artístico', p: 'Murales y artes plásticas hechos a tu medida, con artistas de CUCO ARTS y la comunidad local.', cta: 'Cotizar una obra' },
    sell: { h: '¿Quieres vender tu obra en store.cucoarts.com?', p: 'Envíanos tu catálogo y tus datos para contactarte.', cta: 'Ver cómo entrar' },
    expo: { h: 'Expo activa en Santiago', p: 'CUCO ARTS × HUSKY Coffee Shop: una exposición temporal de arte local. Conoce el proyecto, a los artistas y la obra que puedes llevarte.', cta: 'Ver la expo' },
    events: { h: 'Eventos y cultura viva en MTY', p: 'Estamos preparando una agenda de eventos y cultura viva de Monterrey.', cta: 'Próximamente' },
  },
  sell: {
    label: 'Para artistas',
    title: '¿Quieres vender tu obra en store.cucoarts.com?',
    lede: 'Cuéntanos quién eres y mándanos tu catálogo. Te contactamos para ver cómo entrar a la tienda.',
    open: 'Ver detalles y precio',
    close: 'Ocultar detalles',
    pkgLabel: 'Paquete de registro oficial',
    pkgTitle: 'Registro oficial de CUCO ARTS para la tienda',
    price: '$1,500',
    priceNote: 'MXN',
    stamp: ['IVA', 'INCLUIDO'],
    items: [
      'Fotos profesionales de tus obras: editadas, centradas y bien iluminadas (mínimo 10).',
      'Entrevista en video de 10 preguntas, con iluminación y audio profesionales.',
      'Tomas de tu taller, tu proceso y/o sus alrededores.',
      'De 2 a 3 horas de trabajo.',
    ],
    altTitle: '¿No puedes cubrir la cuota?',
    altText: 'Puedes solicitar la condonación o proponer una colaboración equivalente.',
    ownTitle: '¿Ya tienes ese contenido?',
    ownText: 'Si ya cuentas con fotos y entrevista propias, podemos agregar tus obras sin el paquete: solo pagas la comisión de la tienda y hacemos un acuerdo de trabajo.',
    formTitle: 'Cuéntanos de ti',
    name: 'Nombre',
    email: 'Correo',
    ig: 'Instagram',
    igHint: '@tuusuario',
    portfolio: 'Enlace a tu catálogo y portafolio con precios',
    portfolioHint: 'https://drive.google.com/… o https://we.tl/…',
    portfolioNote: 'Esperamos una liga de Google Drive o WeTransfer con tus obras y sus precios. Revisa que cualquiera con el enlace pueda abrirla o descargarla.',
    option: '¿Cómo te gustaría entrar?',
    opts: {
      paquete: 'Quiero el paquete de registro ($1,500 IVA incluido)',
      condonacion: 'Quiero solicitar condonación o proponer una colaboración equivalente',
      propio: 'Ya tengo mis fotos y mi entrevista (solo comisión y acuerdo de trabajo)',
    },
    collab: 'Qué podrías ofrecer a cambio',
    collabHint: 'Por ejemplo: contenido, difusión, apoyo en eventos…',
    extras: 'Extras',
    extrasHint: 'CV, colección en venta, enlaces a notas o exposiciones, etc.',
    consent: 'Acepto el {privacy} y que CUCO ARTS me contacte por esta solicitud.',
    news: 'Quiero recibir noticias de la tienda (opcional).',
    submit: 'Enviar mi solicitud',
    intro: 'Así llegará tu solicitud a CUCO ARTS. Envíala por WhatsApp o por correo.',
  },
  quote: {
    title: 'Cotizador artístico',
    intro: 'Cuéntanos qué tienes en mente. Te conectamos con artistas de CUCO ARTS y la comunidad local, y te respondemos con una propuesta.',
    type: '¿Qué necesitas?',
    types: { mural: 'Mural', arte: 'Pintura, dibujo o ilustración', escultura: 'Escultura u objeto', otro: 'Otro (diseño, objetos…)' },
    place: '¿Dónde va?',
    places: { interior: 'Interior', exterior: 'Exterior' },
    size: 'Medidas aproximadas',
    width: 'Ancho',
    height: 'Alto',
    unit: 'Unidad',
    idea: 'Cuéntanos tu idea',
    ideaHint: 'Estilo, tema, colores, referencias…',
    budget: 'Presupuesto',
    budgets: ['No sé aún', 'Menos de $10,000', '$10,000 – $25,000', '$25,000 – $50,000', 'Más de $50,000', 'Recomiéndenme'],
    city: 'Ciudad',
    date: '¿Tienes una fecha límite?',
    invoice: '¿Necesitas factura?',
    yes: 'Sí',
    no: 'No',
    name: 'Nombre',
    phone: 'WhatsApp',
    email: 'Correo',
    news: 'Quiero recibir noticias de la tienda (opcional).',
    consentPre: 'Al enviar aceptas el',
    submit: 'Enviar mi solicitud',
    intro2: 'Así llegará tu solicitud a CUCO ARTS. Envíala por WhatsApp o por correo.',
    errName: 'Escribe tu nombre para saber a quién responder.',
    errPhone: 'Revisa tu WhatsApp: necesitamos un número de 10 dígitos para responderte.',
  },
  files: {
    label: 'Archivos (opcional)',
    hintSell: 'Opcional, para archivos pequeños como tu CV o algunas fotos. Hasta 4 de 5 MB (PDF, imágenes, Word o ZIP). Para archivos grandes usa el enlace de arriba.',
    hintQuote: 'Imágenes o documentos de referencia. Hasta 4 archivos de 5 MB (PDF, imágenes, Word o ZIP).',
    choose: 'Elegir archivos',
    remove: 'Quitar',
    errCount: 'Máximo 4 archivos.',
    errSize: 'Cada archivo debe pesar 5 MB o menos, y todos juntos 7 MB.',
    errType: 'Tipo de archivo no permitido. Usa PDF, imágenes, Word o ZIP.',
  },
  status: {
    sending: 'Enviando…',
    sentTitle: 'Listo, recibimos tu solicitud',
    sentSell: 'Te contactaremos al correo que nos diste.',
    sentQuote: 'Te responderemos por WhatsApp o correo.',
    folio: 'Folio',
    again: 'Enviar otra solicitud',
    failed: 'No pudimos enviarla desde aquí. Puedes mandarla por WhatsApp o correo con el mismo mensaje:',
    attachNote: 'Al abrir WhatsApp o tu correo, adjunta ahí tus archivos.',
  },
  events: {
    label: 'Cultura viva',
    title: 'Eventos y cultura viva en MTY',
    text: 'Estamos preparando una agenda de eventos y cultura viva de Monterrey. Pronto la verás aquí.',
    stamp: ['MUY', 'PRONTO'],
    stampFull: 'Próximamente',
  },
  done: { wa: 'Enviar por WhatsApp', mail: 'Enviar por correo', copy: 'Copiar texto', copied: 'Copiado', edit: 'Editar', close: 'Cerrar' },
  privacy: 'aviso de privacidad',
  errors: {
    name: 'Escribe tu nombre.',
    email: 'Revisa tu correo: parece incompleto.',
    ig: 'Escribe tu Instagram para conocer tu obra.',
    portfolio: 'Pega un enlace de Google Drive o WeTransfer que empiece con https://',
    consent: 'Marca la casilla de aceptación para poder continuar.',
  },
  sumQuote: { head: 'Hola CUCO ARTS, quiero cotizar una obra', tipo: 'Tipo', lugar: 'Dónde va', medidas: 'Medidas', idea: 'Idea', presupuesto: 'Presupuesto', ciudad: 'Ciudad', fecha: 'Fecha límite', factura: 'Factura', nombre: 'Nombre', tel: 'WhatsApp', correo: 'Correo', news: 'Quiero recibir noticias', archivos: 'Archivos' },
  sumSell: { head: 'Hola CUCO ARTS, quiero vender mi obra en la tienda', nombre: 'Nombre', correo: 'Correo', ig: 'Instagram', portafolio: 'Enlace al catálogo y portafolio con precios', opcion: 'Opción', colab: 'Puedo ofrecer', extras: 'Extras', news: 'Quiero recibir noticias', archivos: 'Archivos' },
  mailSubjQuote: 'Cotización de obra artística',
  mailSubjSell: 'Quiero vender mi obra en la tienda',
};

type Copy = typeof es;

const en: Copy = {
  htmlTitle: 'CUCO ARTS · Art and culture from Monterrey',
  nav: { store: 'Store', quote: 'Quote', murals: 'Murals', art: 'Custom art', fresh: 'New', sell: 'Sell your art', expo: 'Expo in Santiago', live: 'Live', events: 'Events', label: 'Sections' },
  theme: { toDark: 'Night mode', toLight: 'Day mode' },
  langBtn: { label: 'Cambiar a español', short: 'ES' },
  hero: {
    cornerL: 'CUCOARTS',
    cornerR: 'LOCAL ART',
    title: 'Discover the Monterrey that exists beyond the maps.',
    lede: 'Buy original art by local artists, commission a piece made to your measure, or sell your art with us.',
    cta: 'Visit the store',
    cta2: 'What you can do here',
    expo: 'Live expo in Santiago',
    stamp: ['FROM THE NORTH', 'WITH LOVE'],
    galleryLabel: 'Art and photography from Monterrey',
  },
  credit: { art: 'Artwork by', photo: 'Photo', zone: 'Cultural zone' },
  actionsTitle: 'What would you like to do today?',
  murals: {
    label: 'Murals · New',
    title: 'Your wall, painted by Monterrey artists',
    text: 'Since 2019 we have produced and managed murals with local painters: we connect your idea with the right artist and run the project from start to finish.',
    cta: 'See murals and projects',
    cta2: 'Get a mural quote',
    stamp: ['MURALS', 'MTY'],
    alt: 'Mural painted by local artists in Monterrey',
  },
  art: {
    label: 'Custom art · New',
    title: 'Art, made for you',
    text: 'Paintings, drawings and illustrations made by artists from Monterrey: tell us your idea and we connect you with the right artist.',
    cta: 'Commission my artwork',
    cta2: 'See how it works',
    stamp: ['MADE', 'FOR YOU'],
    alt: 'Original artwork by a local artist from Monterrey',
  },
  about: {
    label: 'About CUCO ARTS',
    title: 'Discover Monterrey through its art and culture',
    text: [
      'CUCO ARTS is a platform for discovering the art, the artists, and the creative spaces of Monterrey. In our online store you will find original work by local artists —painting, printmaking, illustration, and sculpture— with international shipping. We also promote exhibitions and cultural collaborations, and we connect ideas with artists to create murals and custom artworks.',
      'Through our cultural zones project, we aim to bring you closer to the people who create in the city and to explore how art is lived across its different territories: North, South, East, Downtown, and West.',
    ],
    zonesTitle: 'Cultural zones of Monterrey',
    zonesText: 'Explore the city through its artists, its creative spaces, and the stories that make each zone unique.',
    zonesLabel: 'Cultural zones',
    zones: ['North', 'South', 'East', 'Downtown', 'West'],
    soon: 'Cultural map coming soon',
  },
  cards: {
    store: { h: 'Explore the store', p: 'Original art by local artists from Monterrey.', cta: 'Go to store.cucoarts.com' },
    quote: { h: 'Art quote', p: 'Murals and fine art made to your measure, with CUCO ARTS artists and the local community.', cta: 'Get a quote' },
    sell: { h: 'Want to sell your art at store.cucoarts.com?', p: 'Send us your catalog and your details so we can contact you.', cta: 'See how to join' },
    expo: { h: 'Live expo in Santiago', p: 'CUCO ARTS × HUSKY Coffee Shop: a temporary exhibition of local art. Discover the project, the artists, and the work you can take home.', cta: 'See the expo' },
    events: { h: 'Events and living culture in MTY', p: "We're preparing an agenda of events and living culture from Monterrey.", cta: 'Coming soon' },
  },
  sell: {
    label: 'For artists',
    title: 'Want to sell your art at store.cucoarts.com?',
    lede: 'Tell us who you are and send us your catalog. We will contact you to see how to join the store.',
    open: 'See details and price',
    close: 'Hide details',
    pkgLabel: 'Official registration package',
    pkgTitle: 'Official CUCO ARTS registration for the store',
    price: '$1,500',
    priceNote: 'MXN',
    stamp: ['VAT', 'INCLUDED'],
    items: [
      'Professional photos of your artworks: edited, centered and well lit (minimum 10).',
      'A 10-question video interview with professional lighting and audio.',
      'Footage of your studio, your process and/or its surroundings.',
      '2 to 3 hours of work.',
    ],
    altTitle: "Can't cover the fee?",
    altText: 'You can ask for a waiver or propose an equivalent collaboration.',
    ownTitle: 'Already have that content?',
    ownText: 'If you already have your own photos and interview, we can add your artworks without the package: you only pay the store commission and we sign a work agreement.',
    formTitle: 'Tell us about you',
    name: 'Name',
    email: 'Email',
    ig: 'Instagram',
    igHint: '@yourusername',
    portfolio: 'Link to your catalog and portfolio with prices',
    portfolioHint: 'https://drive.google.com/… or https://we.tl/…',
    portfolioNote: 'We expect a Google Drive or WeTransfer link with your artworks and their prices. Check that anyone with the link can open or download it.',
    option: 'How would you like to join?',
    opts: {
      paquete: 'I want the registration package ($1,500 VAT included)',
      condonacion: 'I want to ask for a waiver or propose an equivalent collaboration',
      propio: 'I already have my photos and interview (commission and work agreement only)',
    },
    collab: 'What you could offer in exchange',
    collabHint: 'For example: content, promotion, event support…',
    extras: 'Extras',
    extrasHint: 'CV, collection for sale, links to press or exhibitions, etc.',
    consent: 'I accept the {privacy} and that CUCO ARTS may contact me about this request.',
    news: 'I would like to receive store news (optional).',
    submit: 'Send my request',
    intro: 'This is how your request will reach CUCO ARTS. Send it by WhatsApp or email.',
  },
  quote: {
    title: 'Art quote',
    intro: 'Tell us what you have in mind. We connect you with CUCO ARTS artists and the local community, and reply with a proposal.',
    type: 'What do you need?',
    types: { mural: 'Mural', arte: 'Painting, drawing or illustration', escultura: 'Sculpture or object', otro: 'Other (design, objects…)' },
    place: 'Where will it go?',
    places: { interior: 'Indoors', exterior: 'Outdoors' },
    size: 'Approximate size',
    width: 'Width',
    height: 'Height',
    unit: 'Unit',
    idea: 'Tell us your idea',
    ideaHint: 'Style, theme, colors, references…',
    budget: 'Budget',
    budgets: ['Not sure yet', 'Under $10,000', '$10,000 – $25,000', '$25,000 – $50,000', 'Over $50,000', 'Recommend me'],
    city: 'City',
    date: 'Do you have a deadline?',
    invoice: 'Do you need an invoice?',
    yes: 'Yes',
    no: 'No',
    name: 'Name',
    phone: 'WhatsApp',
    email: 'Email',
    news: 'I would like to receive store news (optional).',
    consentPre: 'By submitting you accept the',
    submit: 'Send my request',
    intro2: 'This is how your request will reach CUCO ARTS. Send it by WhatsApp or email.',
    errName: 'Please type your name so we know who to reply to.',
    errPhone: 'Check your WhatsApp: we need a 10-digit number to reply.',
  },
  files: {
    label: 'Files (optional)',
    hintSell: 'Optional, for small files like your CV or a few photos. Up to 4 files of 5 MB (PDF, images, Word or ZIP). For large files use the link above.',
    hintQuote: 'Reference images or documents. Up to 4 files of 5 MB (PDF, images, Word or ZIP).',
    choose: 'Choose files',
    remove: 'Remove',
    errCount: 'Up to 4 files.',
    errSize: 'Each file must be 5 MB or less, and 7 MB all together.',
    errType: 'File type not allowed. Use PDF, images, Word or ZIP.',
  },
  status: {
    sending: 'Sending…',
    sentTitle: 'Done, we received your request',
    sentSell: 'We will contact you at the email you gave us.',
    sentQuote: 'We will reply by WhatsApp or email.',
    folio: 'Reference',
    again: 'Send another request',
    failed: "We couldn't send it from here. You can send it by WhatsApp or email with the same message:",
    attachNote: 'When WhatsApp or your email opens, attach your files there.',
  },
  events: {
    label: 'Living culture',
    title: 'Events and living culture in MTY',
    text: "We're preparing an agenda of events and living culture from Monterrey. You'll see it here soon.",
    stamp: ['COMING', 'SOON'],
    stampFull: 'Coming soon',
  },
  done: { wa: 'Send via WhatsApp', mail: 'Send by email', copy: 'Copy text', copied: 'Copied', edit: 'Edit', close: 'Close' },
  privacy: 'privacy notice',
  errors: {
    name: 'Please type your name.',
    email: 'Check your email: it looks incomplete.',
    ig: 'Please add your Instagram so we can see your work.',
    portfolio: 'Paste a Google Drive or WeTransfer link that starts with https://',
    consent: 'Please tick the acceptance box to continue.',
  },
  sumQuote: { head: "Hi CUCO ARTS, I'd like a quote for an artwork", tipo: 'Type', lugar: 'Where', medidas: 'Size', idea: 'Idea', presupuesto: 'Budget', ciudad: 'City', fecha: 'Deadline', factura: 'Invoice', nombre: 'Name', tel: 'WhatsApp', correo: 'Email', news: "I'd like to receive news", archivos: 'Files' },
  sumSell: { head: "Hi CUCO ARTS, I'd like to sell my art in the store", nombre: 'Name', correo: 'Email', ig: 'Instagram', portafolio: 'Link to catalog and portfolio with prices', opcion: 'Option', colab: 'I can offer', extras: 'Extras', news: "I'd like to receive news", archivos: 'Files' },
  mailSubjQuote: 'Art quote request',
  mailSubjSell: 'I want to sell my art in the store',
};

export const COPY: Record<Lang, Copy> = { es, en };
export type { Copy };
